/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_raise_practice_jni_JNI */

#define TAG "com_raise_practice_jni_JNI"

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)


#ifndef _Included_com_raise_practice_jni_JNI
#define _Included_com_raise_practice_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_raise_practice_jni_JNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_raise_practice_jni_JNI_sayHello
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
