/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_raise_practice_jni_JNI.h"
#include "comm_prot_jni_tool.c"
/* Header for class com_raise_practice_jni_JNI */


/*
 * Class:     com_raise_practice_jni_JNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_raise_practice_jni_JNI_sayHello
        (JNIEnv *env, jclass jclazz, jstring jname) {
    LOGD("Java_com_raise_practice_jni_JNI_sayHello start.");
    //public static java.lang.String sayHelloFromCPP(java.lang.String);
    //    descriptor: (Ljava/lang/String;)Ljava/lang/String;
    //找类
    jclass cls = (*env)->FindClass(env, "com/raise/practice/jni/JNI");
    //找方法
    jmethodID jmethodId = (*env)->GetStaticMethodID(env, cls, (const char *) "sayHelloFromCPP",
                                                    "(Ljava/lang/String;)Ljava/lang/String;");
    //调用方法
    jstring jstring1 = (*env)->CallStaticObjectMethod(env, cls, jmethodId, NULL);

    LOGD("Java_com_raise_practice_jni_JNI_sayHello sayHelloFromCPP：%s",
         jstring2chars(env, jstring1));
    return jname;
    //return "hello $1";
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    LOGD("JNI_OnLoad start.");
    return JNI_VERSION_1_4;
}